name: build
run-name: build
on: [push]

jobs:
  build:
    runs-on: linux
    steps:
      - uses: actions/checkout@v4
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: gitea.mrmoku.de
          username: ${{secrets.USER}}
          password: ${{secrets.TOKEN}}
      - name: build and push docker image
        uses: docker/build-push-action@v5 
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "gitea.mrmoku.de/pablo/weather:latest"

