export const weatherCodeMap: Record<number, WeatherInfo> = {
  0: { description: "Clear sky", icon: "☀️" },
  1: { description: "Mainly clear", icon: "🌤" },
  2: { description: "Partly cloudy", icon: "⛅" },
  3: { description: "Overcast", icon: "☁️" },
  45: { description: "Fog", icon: "🌫" },
  48: { description: "Depositing rime fog", icon: "🌫❄️" },
  51: { description: "Light drizzle", icon: "🌦" },
  53: { description: "Moderate drizzle", icon: "🌧" },
  55: { description: "Dense drizzle", icon: "🌧" },
  56: { description: "Freezing drizzle (light)", icon: "🌧❄️" },
  57: { description: "Freezing drizzle (dense)", icon: "🌧❄️" },
  61: { description: "Slight rain", icon: "🌧" },
  63: { description: "Moderate rain", icon: "🌧💧" },
  65: { description: "Heavy rain", icon: "🌧🌊" },
  66: { description: "Freezing rain (light)", icon: "🌧❄️" },
  67: { description: "Freezing rain (heavy)", icon: "🌧❄️❄️" },
  71: { description: "Slight snow fall", icon: "🌨" },
  73: { description: "Moderate snow fall", icon: "🌨❄️" },
  75: { description: "Heavy snow fall", icon: "❄️❄️" },
  77: { description: "Snow grains", icon: "❄️" },
  80: { description: "Rain showers (slight)", icon: "🌦" },
  81: { description: "Rain showers (moderate)", icon: "🌧" },
  82: { description: "Rain showers (violent)", icon: "🌧🌩" },
  85: { description: "Snow showers (slight)", icon: "🌨" },
  86: { description: "Snow showers (heavy)", icon: "❄️🌨" },
  95: { description: "Thunderstorm", icon: "🌩" },
  96: { description: "Thunderstorm with slight hail", icon: "🌩🌨" },
  99: { description: "Thunderstorm with heavy hail", icon: "🌩❄️" },
};
